name: Simple VPS Deployment (Git Pull & Migrate)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy and Run Commands via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          
          script: |
            cd /var/www/html
            
            git pull origin main
            
            php migrate.php --force
            
            php seed_db.php